#!/bin/bash
# Clean N9 ROM Build
export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
./prebuilts/sdk/tools/jack-admin kill-server
./prebuilts/sdk/tools/jack-admin start-server
source build/envsetup.sh
make clobber
breakfast flounder
export USE_CCACHE=1
mka bacon
